// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpWWFQ6FGoY0C5Ay87ArguUlRQlxGWr98',
    appId: '1:1030792127075:web:d44394ae8a105d0f9c0e56',
    messagingSenderId: '1030792127075',
    projectId: 'banking-app-c014f',
    authDomain: 'banking-app-c014f.firebaseapp.com',
    storageBucket: 'banking-app-c014f.appspot.com',
    measurementId: 'G-RWW63TD12T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChklY9uH_NktobvH6Ic8FLj0_wHI8IAqU',
    appId: '1:1030792127075:android:cf11b0d5d0dd2af09c0e56',
    messagingSenderId: '1030792127075',
    projectId: 'banking-app-c014f',
    storageBucket: 'banking-app-c014f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkeKVhEmwxOd_rwPmZPLthR3lskRI_dic',
    appId: '1:1030792127075:ios:616e7483c01c07269c0e56',
    messagingSenderId: '1030792127075',
    projectId: 'banking-app-c014f',
    storageBucket: 'banking-app-c014f.appspot.com',
    iosClientId: '1030792127075-l5ck5c3c0h3uipnic7f0n719h0a0haut.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkeKVhEmwxOd_rwPmZPLthR3lskRI_dic',
    appId: '1:1030792127075:ios:616e7483c01c07269c0e56',
    messagingSenderId: '1030792127075',
    projectId: 'banking-app-c014f',
    storageBucket: 'banking-app-c014f.appspot.com',
    iosClientId: '1030792127075-l5ck5c3c0h3uipnic7f0n719h0a0haut.apps.googleusercontent.com',
    iosBundleId: 'com.example.bankingApp',
  );
}
